source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.3", ">= 7.1.3.2"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# Add these gems to the Gemfile
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'jwt', '~> 2.5'
gem 'rack-cors'
gem 'active_model_serializers', '~> 0.10.12'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
end

